### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by itamayo** [cwi-dis/traction-test#1]
First of all great job, well done !!

I got this error when docker starts:

```bash
$ node --enable-source-maps ./bin/backend.js
web_1    | internal/modules/cjs/loader.js:979
web_1    |   throw err;
web_1    |   ^
web_1    | 
web_1    | Error: Cannot find module '/code/bin/backend.js'
web_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
web_1    |     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
web_1    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
web_1    |     at internal/main/run_main_module.js:17:47 {
web_1    |   code: 'MODULE_NOT_FOUND',
web_1    |   requireStack: []
web_1    | }
web_1    | error Command failed with exit code 1.
```
What could be ?

**Comment by troeggla** [comment]
Hey, thanks!

Did you start the application through `docker-compose`? If so, then it's probably that the `webpack` bundle generated when building the container is overridden when the local directory is mounted inside the container (which does not have the bundle). So you could either remove the `volumes` section in `docker-compose.yml` under `web` to prevent to local directory from being mounted, or rebuild the bundle locally by running `yarn run webpack` before starting the containers.

That said, there is some more configuration that is read from environment variables (service endpoints, SNS topic channels, bucket names, AWS credentials) which I haven't included in the repository because they are sensitive information. I will deploy the app on an EC2 instance later today so you can take a look at it.

**Comment by itamayo** [comment]
I used docker-compose, without docker, it throws same error;  folder bin/ doesn't exist, anyway whether you are thinking on deploying  to aws it is ok.

**Comment by troeggla** [comment]
So while deploying on AWS today I realised that I actually did forget to compile the bundle in the `Dockerfile`. I added the relevant code and closed the issue. I will send a link to the running AWS instance in a bit.

**Comment by itamayo** [comment]
Great ! Elegant solution for beginning let's see what could be best solution for Traction.
